/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AchCreateCreditPaymentRequestAccountHolder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AchCreateCreditPaymentRequest
 */
public class AchCreateCreditPaymentRequestTest {
    private final AchCreateCreditPaymentRequest model = new AchCreateCreditPaymentRequest();

    /**
     * Model tests for AchCreateCreditPaymentRequest
     */
    @Test
    public void testAchCreateCreditPaymentRequest() {
        // TODO: test AchCreateCreditPaymentRequest
    }

    /**
     * Test the property 'merchantGuid'
     */
    @Test
    public void merchantGuidTest() {
        // TODO: test merchantGuid
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'payeeName'
     */
    @Test
    public void payeeNameTest() {
        // TODO: test payeeName
    }

    /**
     * Test the property 'statementCompanyName'
     */
    @Test
    public void statementCompanyNameTest() {
        // TODO: test statementCompanyName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'accountHolder'
     */
    @Test
    public void accountHolderTest() {
        // TODO: test accountHolder
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'sequenceNumber'
     */
    @Test
    public void sequenceNumberTest() {
        // TODO: test sequenceNumber
    }

    /**
     * Test the property 'associationId'
     */
    @Test
    public void associationIdTest() {
        // TODO: test associationId
    }

}
