/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardUpdateCardDetailsRequest
 */
public class CardUpdateCardDetailsRequestTest {
    private final CardUpdateCardDetailsRequest model = new CardUpdateCardDetailsRequest();

    /**
     * Model tests for CardUpdateCardDetailsRequest
     */
    @Test
    public void testCardUpdateCardDetailsRequest() {
        // TODO: test CardUpdateCardDetailsRequest
    }

    /**
     * Test the property 'purchaseType'
     */
    @Test
    public void purchaseTypeTest() {
        // TODO: test purchaseType
    }

    /**
     * Test the property 'miDWhitelist'
     */
    @Test
    public void miDWhitelistTest() {
        // TODO: test miDWhitelist
    }

    /**
     * Test the property 'miDBlacklist'
     */
    @Test
    public void miDBlacklistTest() {
        // TODO: test miDBlacklist
    }

    /**
     * Test the property 'usageLimit'
     */
    @Test
    public void usageLimitTest() {
        // TODO: test usageLimit
    }

    /**
     * Test the property 'associationId'
     */
    @Test
    public void associationIdTest() {
        // TODO: test associationId
    }

    /**
     * Test the property 'terminateDate'
     */
    @Test
    public void terminateDateTest() {
        // TODO: test terminateDate
    }

    /**
     * Test the property 'amountLimit'
     */
    @Test
    public void amountLimitTest() {
        // TODO: test amountLimit
    }

}
