/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardIssueCreateVirtualCardLiteRequestTransmission
 */
public class CardIssueCreateVirtualCardLiteRequestTransmissionTest {
    private final CardIssueCreateVirtualCardLiteRequestTransmission model = new CardIssueCreateVirtualCardLiteRequestTransmission();

    /**
     * Model tests for CardIssueCreateVirtualCardLiteRequestTransmission
     */
    @Test
    public void testCardIssueCreateVirtualCardLiteRequestTransmission() {
        // TODO: test CardIssueCreateVirtualCardLiteRequestTransmission
    }

    /**
     * Test the property 'transmissionMethods'
     */
    @Test
    public void transmissionMethodsTest() {
        // TODO: test transmissionMethods
    }

    /**
     * Test the property 'emailRecipient'
     */
    @Test
    public void emailRecipientTest() {
        // TODO: test emailRecipient
    }

    /**
     * Test the property 'merchantPhoneNumber'
     */
    @Test
    public void merchantPhoneNumberTest() {
        // TODO: test merchantPhoneNumber
    }

    /**
     * Test the property 'emailFrom'
     */
    @Test
    public void emailFromTest() {
        // TODO: test emailFrom
    }

    /**
     * Test the property 'recipientName'
     */
    @Test
    public void recipientNameTest() {
        // TODO: test recipientName
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'daysToExpire'
     */
    @Test
    public void daysToExpireTest() {
        // TODO: test daysToExpire
    }

    /**
     * Test the property 'faxFrom'
     */
    @Test
    public void faxFromTest() {
        // TODO: test faxFrom
    }

    /**
     * Test the property 'faxRecipient'
     */
    @Test
    public void faxRecipientTest() {
        // TODO: test faxRecipient
    }

}
