/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DailyAccountingDetail
 */
public class DailyAccountingDetailTest {
    private final DailyAccountingDetail model = new DailyAccountingDetail();

    /**
     * Model tests for DailyAccountingDetail
     */
    @Test
    public void testDailyAccountingDetail() {
        // TODO: test DailyAccountingDetail
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'merchantGuid'
     */
    @Test
    public void merchantGuidTest() {
        // TODO: test merchantGuid
    }

    /**
     * Test the property 'clientName'
     */
    @Test
    public void clientNameTest() {
        // TODO: test clientName
    }

    /**
     * Test the property 'releasedDate'
     */
    @Test
    public void releasedDateTest() {
        // TODO: test releasedDate
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'cardLastFour'
     */
    @Test
    public void cardLastFourTest() {
        // TODO: test cardLastFour
    }

    /**
     * Test the property 'incomingTransactionCode'
     */
    @Test
    public void incomingTransactionCodeTest() {
        // TODO: test incomingTransactionCode
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    public void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'ticketNumber'
     */
    @Test
    public void ticketNumberTest() {
        // TODO: test ticketNumber
    }

    /**
     * Test the property 'entityGuid'
     */
    @Test
    public void entityGuidTest() {
        // TODO: test entityGuid
    }

    /**
     * Test the property 'purchaseType'
     */
    @Test
    public void purchaseTypeTest() {
        // TODO: test purchaseType
    }

    /**
     * Test the property 'entityId'
     */
    @Test
    public void entityIdTest() {
        // TODO: test entityId
    }

    /**
     * Test the property 'issuedAmount'
     */
    @Test
    public void issuedAmountTest() {
        // TODO: test issuedAmount
    }

    /**
     * Test the property 'labelName'
     */
    @Test
    public void labelNameTest() {
        // TODO: test labelName
    }

    /**
     * Test the property 'associationId'
     */
    @Test
    public void associationIdTest() {
        // TODO: test associationId
    }

    /**
     * Test the property 'saleGuid'
     */
    @Test
    public void saleGuidTest() {
        // TODO: test saleGuid
    }

    /**
     * Test the property 'cardGuid'
     */
    @Test
    public void cardGuidTest() {
        // TODO: test cardGuid
    }

    /**
     * Test the property 'dateTime'
     */
    @Test
    public void dateTimeTest() {
        // TODO: test dateTime
    }

}
