/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FundingTransferMerchantCashBalanceRequest
 */
public class FundingTransferMerchantCashBalanceRequestTest {
    private final FundingTransferMerchantCashBalanceRequest model = new FundingTransferMerchantCashBalanceRequest();

    /**
     * Model tests for FundingTransferMerchantCashBalanceRequest
     */
    @Test
    public void testFundingTransferMerchantCashBalanceRequest() {
        // TODO: test FundingTransferMerchantCashBalanceRequest
    }

    /**
     * Test the property 'transferredFrom'
     */
    @Test
    public void transferredFromTest() {
        // TODO: test transferredFrom
    }

    /**
     * Test the property 'transferredTo'
     */
    @Test
    public void transferredToTest() {
        // TODO: test transferredTo
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

}
