/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SaleCreateTransactionRequestBankAccount;
import com.konfigthis.client.model.SaleCreateTransactionRequestBrowserData;
import com.konfigthis.client.model.SaleCreateTransactionRequestCard;
import com.konfigthis.client.model.SaleCreateTransactionRequestConnexPayTransaction;
import com.konfigthis.client.model.SaleCreateTransactionRequestCustomParametersInner;
import com.konfigthis.client.model.SaleCreateTransactionRequestCustomer;
import com.konfigthis.client.model.SaleCreateTransactionRequestEnhancedData;
import com.konfigthis.client.model.SaleCreateTransactionRequestRiskData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SaleCreateTransactionRequest
 */
public class SaleCreateTransactionRequestTest {
    private final SaleCreateTransactionRequest model = new SaleCreateTransactionRequest();

    /**
     * Model tests for SaleCreateTransactionRequest
     */
    @Test
    public void testSaleCreateTransactionRequest() {
        // TODO: test SaleCreateTransactionRequest
    }

    /**
     * Test the property 'deviceGuid'
     */
    @Test
    public void deviceGuidTest() {
        // TODO: test deviceGuid
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'tenderType'
     */
    @Test
    public void tenderTypeTest() {
        // TODO: test tenderType
    }

    /**
     * Test the property 'sequenceNumber'
     */
    @Test
    public void sequenceNumberTest() {
        // TODO: test sequenceNumber
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'sendReceipt'
     */
    @Test
    public void sendReceiptTest() {
        // TODO: test sendReceipt
    }

    /**
     * Test the property 'riskProcessingOnly'
     */
    @Test
    public void riskProcessingOnlyTest() {
        // TODO: test riskProcessingOnly
    }

    /**
     * Test the property 'statementDescription'
     */
    @Test
    public void statementDescriptionTest() {
        // TODO: test statementDescription
    }

    /**
     * Test the property 'customerID'
     */
    @Test
    public void customerIDTest() {
        // TODO: test customerID
    }

    /**
     * Test the property 'activationDate'
     */
    @Test
    public void activationDateTest() {
        // TODO: test activationDate
    }

    /**
     * Test the property 'requestIp'
     */
    @Test
    public void requestIpTest() {
        // TODO: test requestIp
    }

    /**
     * Test the property 'connexPayTransaction'
     */
    @Test
    public void connexPayTransactionTest() {
        // TODO: test connexPayTransaction
    }

    /**
     * Test the property 'riskData'
     */
    @Test
    public void riskDataTest() {
        // TODO: test riskData
    }

    /**
     * Test the property 'card'
     */
    @Test
    public void cardTest() {
        // TODO: test card
    }

    /**
     * Test the property 'bankAccount'
     */
    @Test
    public void bankAccountTest() {
        // TODO: test bankAccount
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'enhancedData'
     */
    @Test
    public void enhancedDataTest() {
        // TODO: test enhancedData
    }

    /**
     * Test the property 'associationId'
     */
    @Test
    public void associationIdTest() {
        // TODO: test associationId
    }

    /**
     * Test the property 'customParameters'
     */
    @Test
    public void customParametersTest() {
        // TODO: test customParameters
    }

    /**
     * Test the property 'labelIDs'
     */
    @Test
    public void labelIDsTest() {
        // TODO: test labelIDs
    }

    /**
     * Test the property 'browserData'
     */
    @Test
    public void browserDataTest() {
        // TODO: test browserData
    }

}
