/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SaleSearchSalesResponseSearchResultDTOInnerCard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SaleSearchSalesResponseSearchResultDTOInner
 */
public class SaleSearchSalesResponseSearchResultDTOInnerTest {
    private final SaleSearchSalesResponseSearchResultDTOInner model = new SaleSearchSalesResponseSearchResultDTOInner();

    /**
     * Model tests for SaleSearchSalesResponseSearchResultDTOInner
     */
    @Test
    public void testSaleSearchSalesResponseSearchResultDTOInner() {
        // TODO: test SaleSearchSalesResponseSearchResultDTOInner
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'card'
     */
    @Test
    public void cardTest() {
        // TODO: test card
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'orderDate'
     */
    @Test
    public void orderDateTest() {
        // TODO: test orderDate
    }

    /**
     * Test the property 'timeStamp'
     */
    @Test
    public void timeStampTest() {
        // TODO: test timeStamp
    }

    /**
     * Test the property 'customerID'
     */
    @Test
    public void customerIDTest() {
        // TODO: test customerID
    }

    /**
     * Test the property 'processorResponseMessage'
     */
    @Test
    public void processorResponseMessageTest() {
        // TODO: test processorResponseMessage
    }

    /**
     * Test the property 'effectiveAmount'
     */
    @Test
    public void effectiveAmountTest() {
        // TODO: test effectiveAmount
    }

    /**
     * Test the property 'batchStatus'
     */
    @Test
    public void batchStatusTest() {
        // TODO: test batchStatus
    }

    /**
     * Test the property 'relatedVoid'
     */
    @Test
    public void relatedVoidTest() {
        // TODO: test relatedVoid
    }

    /**
     * Test the property 'relatedReturns'
     */
    @Test
    public void relatedReturnsTest() {
        // TODO: test relatedReturns
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'deviceGuid'
     */
    @Test
    public void deviceGuidTest() {
        // TODO: test deviceGuid
    }

    /**
     * Test the property 'captureGuid'
     */
    @Test
    public void captureGuidTest() {
        // TODO: test captureGuid
    }

    /**
     * Test the property 'customData'
     */
    @Test
    public void customDataTest() {
        // TODO: test customData
    }

    /**
     * Test the property 'generatedByCapture'
     */
    @Test
    public void generatedByCaptureTest() {
        // TODO: test generatedByCapture
    }

    /**
     * Test the property 'partiallyApprovedAmount'
     */
    @Test
    public void partiallyApprovedAmountTest() {
        // TODO: test partiallyApprovedAmount
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'surcharge'
     */
    @Test
    public void surchargeTest() {
        // TODO: test surcharge
    }

    /**
     * Test the property 'surchargeType'
     */
    @Test
    public void surchargeTypeTest() {
        // TODO: test surchargeType
    }

    /**
     * Test the property 'serviceFee'
     */
    @Test
    public void serviceFeeTest() {
        // TODO: test serviceFee
    }

    /**
     * Test the property 'tipAmount'
     */
    @Test
    public void tipAmountTest() {
        // TODO: test tipAmount
    }

    /**
     * Test the property 'cardDataSource'
     */
    @Test
    public void cardDataSourceTest() {
        // TODO: test cardDataSource
    }

    /**
     * Test the property 'allowCardEmv'
     */
    @Test
    public void allowCardEmvTest() {
        // TODO: test allowCardEmv
    }

    /**
     * Test the property 'incomingTransactionCode'
     */
    @Test
    public void incomingTransactionCodeTest() {
        // TODO: test incomingTransactionCode
    }

    /**
     * Test the property 'activationDate'
     */
    @Test
    public void activationDateTest() {
        // TODO: test activationDate
    }

}
