/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.StatusGroup3DsAuthenticationStatusResponseCard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StatusGroup3DsAuthenticationStatusResponse
 */
public class StatusGroup3DsAuthenticationStatusResponseTest {
    private final StatusGroup3DsAuthenticationStatusResponse model = new StatusGroup3DsAuthenticationStatusResponse();

    /**
     * Model tests for StatusGroup3DsAuthenticationStatusResponse
     */
    @Test
    public void testStatusGroup3DsAuthenticationStatusResponse() {
        // TODO: test StatusGroup3DsAuthenticationStatusResponse
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'timeStamp'
     */
    @Test
    public void timeStampTest() {
        // TODO: test timeStamp
    }

    /**
     * Test the property 'deviceGuid'
     */
    @Test
    public void deviceGuidTest() {
        // TODO: test deviceGuid
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'secureData'
     */
    @Test
    public void secureDataTest() {
        // TODO: test secureData
    }

    /**
     * Test the property 'eci'
     */
    @Test
    public void eciTest() {
        // TODO: test eci
    }

    /**
     * Test the property 'cavv'
     */
    @Test
    public void cavvTest() {
        // TODO: test cavv
    }

    /**
     * Test the property 'directoryServerTransactionID'
     */
    @Test
    public void directoryServerTransactionIDTest() {
        // TODO: test directoryServerTransactionID
    }

    /**
     * Test the property 'acsTransactionId'
     */
    @Test
    public void acsTransactionIdTest() {
        // TODO: test acsTransactionId
    }

    /**
     * Test the property 'card'
     */
    @Test
    public void cardTest() {
        // TODO: test card
    }

    /**
     * Test the property 'processorResponseCode'
     */
    @Test
    public void processorResponseCodeTest() {
        // TODO: test processorResponseCode
    }

    /**
     * Test the property 'processorMessage'
     */
    @Test
    public void processorMessageTest() {
        // TODO: test processorMessage
    }

}
