/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionSearchVirtualCardHistoryResponseTransactionsInner
 */
public class TransactionSearchVirtualCardHistoryResponseTransactionsInnerTest {
    private final TransactionSearchVirtualCardHistoryResponseTransactionsInner model = new TransactionSearchVirtualCardHistoryResponseTransactionsInner();

    /**
     * Model tests for TransactionSearchVirtualCardHistoryResponseTransactionsInner
     */
    @Test
    public void testTransactionSearchVirtualCardHistoryResponseTransactionsInner() {
        // TODO: test TransactionSearchVirtualCardHistoryResponseTransactionsInner
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
