/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TransactionCreateAchCreditPaymentRequestAccountHolder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionCreateAchCreditPaymentRequest
 */
public class TransactionCreateAchCreditPaymentRequestTest {
    private final TransactionCreateAchCreditPaymentRequest model = new TransactionCreateAchCreditPaymentRequest();

    /**
     * Model tests for TransactionCreateAchCreditPaymentRequest
     */
    @Test
    public void testTransactionCreateAchCreditPaymentRequest() {
        // TODO: test TransactionCreateAchCreditPaymentRequest
    }

    /**
     * Test the property 'merchantGuid'
     */
    @Test
    public void merchantGuidTest() {
        // TODO: test merchantGuid
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'payeeName'
     */
    @Test
    public void payeeNameTest() {
        // TODO: test payeeName
    }

    /**
     * Test the property 'statementCompanyName'
     */
    @Test
    public void statementCompanyNameTest() {
        // TODO: test statementCompanyName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'incomingTransactionCode'
     */
    @Test
    public void incomingTransactionCodeTest() {
        // TODO: test incomingTransactionCode
    }

    /**
     * Test the property 'accountHolder'
     */
    @Test
    public void accountHolderTest() {
        // TODO: test accountHolder
    }

}
