/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ValidationSearchVerifyOperationResponseSearchResultDTOInnerCard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ValidationSearchVerifyOperationResponseSearchResultDTOInner
 */
public class ValidationSearchVerifyOperationResponseSearchResultDTOInnerTest {
    private final ValidationSearchVerifyOperationResponseSearchResultDTOInner model = new ValidationSearchVerifyOperationResponseSearchResultDTOInner();

    /**
     * Model tests for ValidationSearchVerifyOperationResponseSearchResultDTOInner
     */
    @Test
    public void testValidationSearchVerifyOperationResponseSearchResultDTOInner() {
        // TODO: test ValidationSearchVerifyOperationResponseSearchResultDTOInner
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'card'
     */
    @Test
    public void cardTest() {
        // TODO: test card
    }

    /**
     * Test the property 'timeStamp'
     */
    @Test
    public void timeStampTest() {
        // TODO: test timeStamp
    }

    /**
     * Test the property 'processorStatusCode'
     */
    @Test
    public void processorStatusCodeTest() {
        // TODO: test processorStatusCode
    }

}
