/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ValidationSearchVerifyOperationRequest
 */
public class ValidationSearchVerifyOperationRequestTest {
    private final ValidationSearchVerifyOperationRequest model = new ValidationSearchVerifyOperationRequest();

    /**
     * Model tests for ValidationSearchVerifyOperationRequest
     */
    @Test
    public void testValidationSearchVerifyOperationRequest() {
        // TODO: test ValidationSearchVerifyOperationRequest
    }

    /**
     * Test the property 'merchantGuid'
     */
    @Test
    public void merchantGuidTest() {
        // TODO: test merchantGuid
    }

    /**
     * Test the property 'cardLastFour'
     */
    @Test
    public void cardLastFourTest() {
        // TODO: test cardLastFour
    }

    /**
     * Test the property 'cardHolderName'
     */
    @Test
    public void cardHolderNameTest() {
        // TODO: test cardHolderName
    }

    /**
     * Test the property 'cardType'
     */
    @Test
    public void cardTypeTest() {
        // TODO: test cardType
    }

    /**
     * Test the property 'timeStampFrom'
     */
    @Test
    public void timeStampFromTest() {
        // TODO: test timeStampFrom
    }

    /**
     * Test the property 'timeStampTo'
     */
    @Test
    public void timeStampToTest() {
        // TODO: test timeStampTo
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
