/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VoidCreateVoidResponseSale;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoidCreateVoidResponse
 */
public class VoidCreateVoidResponseTest {
    private final VoidCreateVoidResponse model = new VoidCreateVoidResponse();

    /**
     * Model tests for VoidCreateVoidResponse
     */
    @Test
    public void testVoidCreateVoidResponse() {
        // TODO: test VoidCreateVoidResponse
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'batchStatus'
     */
    @Test
    public void batchStatusTest() {
        // TODO: test batchStatus
    }

    /**
     * Test the property 'timeStamp'
     */
    @Test
    public void timeStampTest() {
        // TODO: test timeStamp
    }

    /**
     * Test the property 'deviceGuid'
     */
    @Test
    public void deviceGuidTest() {
        // TODO: test deviceGuid
    }

    /**
     * Test the property 'saleGuid'
     */
    @Test
    public void saleGuidTest() {
        // TODO: test saleGuid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'voidReason'
     */
    @Test
    public void voidReasonTest() {
        // TODO: test voidReason
    }

    /**
     * Test the property 'processorStatusCode'
     */
    @Test
    public void processorStatusCodeTest() {
        // TODO: test processorStatusCode
    }

    /**
     * Test the property 'wasProcessed'
     */
    @Test
    public void wasProcessedTest() {
        // TODO: test wasProcessed
    }

    /**
     * Test the property 'batchGuid'
     */
    @Test
    public void batchGuidTest() {
        // TODO: test batchGuid
    }

    /**
     * Test the property 'authCode'
     */
    @Test
    public void authCodeTest() {
        // TODO: test authCode
    }

    /**
     * Test the property 'refNumber'
     */
    @Test
    public void refNumberTest() {
        // TODO: test refNumber
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    public void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'customerReceipt'
     */
    @Test
    public void customerReceiptTest() {
        // TODO: test customerReceipt
    }

    /**
     * Test the property 'sequenceNumber'
     */
    @Test
    public void sequenceNumberTest() {
        // TODO: test sequenceNumber
    }

    /**
     * Test the property 'sale'
     */
    @Test
    public void saleTest() {
        // TODO: test sale
    }

}
