/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VoidSearchVoidsResponseSearchResultDTOInnerSaleCard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoidSearchVoidsResponseSearchResultDTOInnerSale
 */
public class VoidSearchVoidsResponseSearchResultDTOInnerSaleTest {
    private final VoidSearchVoidsResponseSearchResultDTOInnerSale model = new VoidSearchVoidsResponseSearchResultDTOInnerSale();

    /**
     * Model tests for VoidSearchVoidsResponseSearchResultDTOInnerSale
     */
    @Test
    public void testVoidSearchVoidsResponseSearchResultDTOInnerSale() {
        // TODO: test VoidSearchVoidsResponseSearchResultDTOInnerSale
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'card'
     */
    @Test
    public void cardTest() {
        // TODO: test card
    }

}
