/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CardUpdateDelayedActivationResponseCard
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CardUpdateDelayedActivationResponseCard {
  public static final String SERIALIZED_NAME_CARD_GUID = "cardGuid";
  @SerializedName(SERIALIZED_NAME_CARD_GUID)
  private String cardGuid;

  public static final String SERIALIZED_NAME_AMOUNT_LIMIT = "amountLimit";
  @SerializedName(SERIALIZED_NAME_AMOUNT_LIMIT)
  private Integer amountLimit = 0;

  public static final String SERIALIZED_NAME_USAGE_LIMIT = "usageLimit";
  @SerializedName(SERIALIZED_NAME_USAGE_LIMIT)
  private Integer usageLimit = 0;

  public static final String SERIALIZED_NAME_LIMIT_WINDOW = "limitWindow";
  @SerializedName(SERIALIZED_NAME_LIMIT_WINDOW)
  private String limitWindow;

  public static final String SERIALIZED_NAME_EXPIRATION_DATE = "expirationDate";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_DATE)
  private String expirationDate;

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  private String expiration;

  public static final String SERIALIZED_NAME_FIRST_SIX = "firstSix";
  @SerializedName(SERIALIZED_NAME_FIRST_SIX)
  private String firstSix;

  public static final String SERIALIZED_NAME_LAST_FOUR = "lastFour";
  @SerializedName(SERIALIZED_NAME_LAST_FOUR)
  private String lastFour;

  public static final String SERIALIZED_NAME_NAME_LINE1 = "nameLine1";
  @SerializedName(SERIALIZED_NAME_NAME_LINE1)
  private String nameLine1;

  public static final String SERIALIZED_NAME_NAME_LINE2 = "nameLine2";
  @SerializedName(SERIALIZED_NAME_NAME_LINE2)
  private String nameLine2;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_ACTIVATION_DATE = "activationDate";
  @SerializedName(SERIALIZED_NAME_ACTIVATION_DATE)
  private String activationDate;

  public static final String SERIALIZED_NAME_CARD_TYPE = "cardType";
  @SerializedName(SERIALIZED_NAME_CARD_TYPE)
  private String cardType;

  public CardUpdateDelayedActivationResponseCard() {
  }

  public CardUpdateDelayedActivationResponseCard cardGuid(String cardGuid) {
    
    
    
    
    this.cardGuid = cardGuid;
    return this;
  }

   /**
   * Get cardGuid
   * @return cardGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1c2a5ec3-67fe-4f2d-984b-fa8acb66a2f3", value = "")

  public String getCardGuid() {
    return cardGuid;
  }


  public void setCardGuid(String cardGuid) {
    
    
    
    this.cardGuid = cardGuid;
  }


  public CardUpdateDelayedActivationResponseCard amountLimit(Integer amountLimit) {
    
    
    
    
    this.amountLimit = amountLimit;
    return this;
  }

   /**
   * Get amountLimit
   * @return amountLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "22", value = "")

  public Integer getAmountLimit() {
    return amountLimit;
  }


  public void setAmountLimit(Integer amountLimit) {
    
    
    
    this.amountLimit = amountLimit;
  }


  public CardUpdateDelayedActivationResponseCard usageLimit(Integer usageLimit) {
    
    
    
    
    this.usageLimit = usageLimit;
    return this;
  }

   /**
   * Get usageLimit
   * @return usageLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "")

  public Integer getUsageLimit() {
    return usageLimit;
  }


  public void setUsageLimit(Integer usageLimit) {
    
    
    
    this.usageLimit = usageLimit;
  }


  public CardUpdateDelayedActivationResponseCard limitWindow(String limitWindow) {
    
    
    
    
    this.limitWindow = limitWindow;
    return this;
  }

   /**
   * Get limitWindow
   * @return limitWindow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "LIFETIME", value = "")

  public String getLimitWindow() {
    return limitWindow;
  }


  public void setLimitWindow(String limitWindow) {
    
    
    
    this.limitWindow = limitWindow;
  }


  public CardUpdateDelayedActivationResponseCard expirationDate(String expirationDate) {
    
    
    
    
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-12-24T23:59:59", value = "")

  public String getExpirationDate() {
    return expirationDate;
  }


  public void setExpirationDate(String expirationDate) {
    
    
    
    this.expirationDate = expirationDate;
  }


  public CardUpdateDelayedActivationResponseCard expiration(String expiration) {
    
    
    
    
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1222", value = "")

  public String getExpiration() {
    return expiration;
  }


  public void setExpiration(String expiration) {
    
    
    
    this.expiration = expiration;
  }


  public CardUpdateDelayedActivationResponseCard firstSix(String firstSix) {
    
    
    
    
    this.firstSix = firstSix;
    return this;
  }

   /**
   * Get firstSix
   * @return firstSix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "111111", value = "")

  public String getFirstSix() {
    return firstSix;
  }


  public void setFirstSix(String firstSix) {
    
    
    
    this.firstSix = firstSix;
  }


  public CardUpdateDelayedActivationResponseCard lastFour(String lastFour) {
    
    
    
    
    this.lastFour = lastFour;
    return this;
  }

   /**
   * Get lastFour
   * @return lastFour
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0717", value = "")

  public String getLastFour() {
    return lastFour;
  }


  public void setLastFour(String lastFour) {
    
    
    
    this.lastFour = lastFour;
  }


  public CardUpdateDelayedActivationResponseCard nameLine1(String nameLine1) {
    
    
    
    
    this.nameLine1 = nameLine1;
    return this;
  }

   /**
   * Get nameLine1
   * @return nameLine1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ping", value = "")

  public String getNameLine1() {
    return nameLine1;
  }


  public void setNameLine1(String nameLine1) {
    
    
    
    this.nameLine1 = nameLine1;
  }


  public CardUpdateDelayedActivationResponseCard nameLine2(String nameLine2) {
    
    
    
    
    this.nameLine2 = nameLine2;
    return this;
  }

   /**
   * Get nameLine2
   * @return nameLine2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lite", value = "")

  public String getNameLine2() {
    return nameLine2;
  }


  public void setNameLine2(String nameLine2) {
    
    
    
    this.nameLine2 = nameLine2;
  }


  public CardUpdateDelayedActivationResponseCard status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Card - Active, but delayed Activation Auth Limit of $1.0 applied.", value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public CardUpdateDelayedActivationResponseCard activationDate(String activationDate) {
    
    
    
    
    this.activationDate = activationDate;
    return this;
  }

   /**
   * Get activationDate
   * @return activationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12/3/2021", value = "")

  public String getActivationDate() {
    return activationDate;
  }


  public void setActivationDate(String activationDate) {
    
    
    
    this.activationDate = activationDate;
  }


  public CardUpdateDelayedActivationResponseCard cardType(String cardType) {
    
    
    
    
    this.cardType = cardType;
    return this;
  }

   /**
   * Get cardType
   * @return cardType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Other", value = "")

  public String getCardType() {
    return cardType;
  }


  public void setCardType(String cardType) {
    
    
    
    this.cardType = cardType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CardUpdateDelayedActivationResponseCard instance itself
   */
  public CardUpdateDelayedActivationResponseCard putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardUpdateDelayedActivationResponseCard cardUpdateDelayedActivationResponseCard = (CardUpdateDelayedActivationResponseCard) o;
    return Objects.equals(this.cardGuid, cardUpdateDelayedActivationResponseCard.cardGuid) &&
        Objects.equals(this.amountLimit, cardUpdateDelayedActivationResponseCard.amountLimit) &&
        Objects.equals(this.usageLimit, cardUpdateDelayedActivationResponseCard.usageLimit) &&
        Objects.equals(this.limitWindow, cardUpdateDelayedActivationResponseCard.limitWindow) &&
        Objects.equals(this.expirationDate, cardUpdateDelayedActivationResponseCard.expirationDate) &&
        Objects.equals(this.expiration, cardUpdateDelayedActivationResponseCard.expiration) &&
        Objects.equals(this.firstSix, cardUpdateDelayedActivationResponseCard.firstSix) &&
        Objects.equals(this.lastFour, cardUpdateDelayedActivationResponseCard.lastFour) &&
        Objects.equals(this.nameLine1, cardUpdateDelayedActivationResponseCard.nameLine1) &&
        Objects.equals(this.nameLine2, cardUpdateDelayedActivationResponseCard.nameLine2) &&
        Objects.equals(this.status, cardUpdateDelayedActivationResponseCard.status) &&
        Objects.equals(this.activationDate, cardUpdateDelayedActivationResponseCard.activationDate) &&
        Objects.equals(this.cardType, cardUpdateDelayedActivationResponseCard.cardType)&&
        Objects.equals(this.additionalProperties, cardUpdateDelayedActivationResponseCard.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardGuid, amountLimit, usageLimit, limitWindow, expirationDate, expiration, firstSix, lastFour, nameLine1, nameLine2, status, activationDate, cardType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardUpdateDelayedActivationResponseCard {\n");
    sb.append("    cardGuid: ").append(toIndentedString(cardGuid)).append("\n");
    sb.append("    amountLimit: ").append(toIndentedString(amountLimit)).append("\n");
    sb.append("    usageLimit: ").append(toIndentedString(usageLimit)).append("\n");
    sb.append("    limitWindow: ").append(toIndentedString(limitWindow)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    firstSix: ").append(toIndentedString(firstSix)).append("\n");
    sb.append("    lastFour: ").append(toIndentedString(lastFour)).append("\n");
    sb.append("    nameLine1: ").append(toIndentedString(nameLine1)).append("\n");
    sb.append("    nameLine2: ").append(toIndentedString(nameLine2)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    activationDate: ").append(toIndentedString(activationDate)).append("\n");
    sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cardGuid");
    openapiFields.add("amountLimit");
    openapiFields.add("usageLimit");
    openapiFields.add("limitWindow");
    openapiFields.add("expirationDate");
    openapiFields.add("expiration");
    openapiFields.add("firstSix");
    openapiFields.add("lastFour");
    openapiFields.add("nameLine1");
    openapiFields.add("nameLine2");
    openapiFields.add("status");
    openapiFields.add("activationDate");
    openapiFields.add("cardType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CardUpdateDelayedActivationResponseCard
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CardUpdateDelayedActivationResponseCard.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CardUpdateDelayedActivationResponseCard is not found in the empty JSON string", CardUpdateDelayedActivationResponseCard.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("cardGuid") != null && !jsonObj.get("cardGuid").isJsonNull()) && !jsonObj.get("cardGuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardGuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardGuid").toString()));
      }
      if ((jsonObj.get("limitWindow") != null && !jsonObj.get("limitWindow").isJsonNull()) && !jsonObj.get("limitWindow").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `limitWindow` to be a primitive type in the JSON string but got `%s`", jsonObj.get("limitWindow").toString()));
      }
      if ((jsonObj.get("expirationDate") != null && !jsonObj.get("expirationDate").isJsonNull()) && !jsonObj.get("expirationDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expirationDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expirationDate").toString()));
      }
      if ((jsonObj.get("expiration") != null && !jsonObj.get("expiration").isJsonNull()) && !jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      if ((jsonObj.get("firstSix") != null && !jsonObj.get("firstSix").isJsonNull()) && !jsonObj.get("firstSix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstSix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstSix").toString()));
      }
      if ((jsonObj.get("lastFour") != null && !jsonObj.get("lastFour").isJsonNull()) && !jsonObj.get("lastFour").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastFour` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastFour").toString()));
      }
      if ((jsonObj.get("nameLine1") != null && !jsonObj.get("nameLine1").isJsonNull()) && !jsonObj.get("nameLine1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameLine1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameLine1").toString()));
      }
      if ((jsonObj.get("nameLine2") != null && !jsonObj.get("nameLine2").isJsonNull()) && !jsonObj.get("nameLine2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameLine2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameLine2").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("activationDate") != null && !jsonObj.get("activationDate").isJsonNull()) && !jsonObj.get("activationDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `activationDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("activationDate").toString()));
      }
      if ((jsonObj.get("cardType") != null && !jsonObj.get("cardType").isJsonNull()) && !jsonObj.get("cardType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CardUpdateDelayedActivationResponseCard.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CardUpdateDelayedActivationResponseCard' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CardUpdateDelayedActivationResponseCard> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CardUpdateDelayedActivationResponseCard.class));

       return (TypeAdapter<T>) new TypeAdapter<CardUpdateDelayedActivationResponseCard>() {
           @Override
           public void write(JsonWriter out, CardUpdateDelayedActivationResponseCard value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CardUpdateDelayedActivationResponseCard read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CardUpdateDelayedActivationResponseCard instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CardUpdateDelayedActivationResponseCard given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CardUpdateDelayedActivationResponseCard
  * @throws IOException if the JSON string is invalid with respect to CardUpdateDelayedActivationResponseCard
  */
  public static CardUpdateDelayedActivationResponseCard fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CardUpdateDelayedActivationResponseCard.class);
  }

 /**
  * Convert an instance of CardUpdateDelayedActivationResponseCard to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

