/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReturnSearchSaleReturnsResponseSearchResultDTOInnerCard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ReturnSearchSaleReturnsResponseSearchResultDTOInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ReturnSearchSaleReturnsResponseSearchResultDTOInner {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private Integer amount = 0;

  public static final String SERIALIZED_NAME_CARD = "card";
  @SerializedName(SERIALIZED_NAME_CARD)
  private ReturnSearchSaleReturnsResponseSearchResultDTOInnerCard card;

  public static final String SERIALIZED_NAME_TIME_STAMP = "timeStamp";
  @SerializedName(SERIALIZED_NAME_TIME_STAMP)
  private String timeStamp;

  public static final String SERIALIZED_NAME_PROCESSOR_STATUS_CODE = "processorStatusCode";
  @SerializedName(SERIALIZED_NAME_PROCESSOR_STATUS_CODE)
  private String processorStatusCode;

  public static final String SERIALIZED_NAME_BATCH_STATUS = "batchStatus";
  @SerializedName(SERIALIZED_NAME_BATCH_STATUS)
  private String batchStatus;

  public static final String SERIALIZED_NAME_GUID = "guid";
  @SerializedName(SERIALIZED_NAME_GUID)
  private String guid;

  public static final String SERIALIZED_NAME_RELATED_VOID = "relatedVoid";
  @SerializedName(SERIALIZED_NAME_RELATED_VOID)
  private Object relatedVoid = null;

  public static final String SERIALIZED_NAME_DEVICE_GUID = "deviceGuid";
  @SerializedName(SERIALIZED_NAME_DEVICE_GUID)
  private String deviceGuid;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_CARD_DATA_SOURCE = "cardDataSource";
  @SerializedName(SERIALIZED_NAME_CARD_DATA_SOURCE)
  private String cardDataSource;

  public static final String SERIALIZED_NAME_ALLOW_CARD_EMV = "allowCardEmv";
  @SerializedName(SERIALIZED_NAME_ALLOW_CARD_EMV)
  private Boolean allowCardEmv = true;

  public ReturnSearchSaleReturnsResponseSearchResultDTOInner() {
  }

  public ReturnSearchSaleReturnsResponseSearchResultDTOInner status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Transaction - Approved", value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner amount(Integer amount) {
    
    
    
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "150", value = "")

  public Integer getAmount() {
    return amount;
  }


  public void setAmount(Integer amount) {
    
    
    
    this.amount = amount;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner card(ReturnSearchSaleReturnsResponseSearchResultDTOInnerCard card) {
    
    
    
    
    this.card = card;
    return this;
  }

   /**
   * Get card
   * @return card
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReturnSearchSaleReturnsResponseSearchResultDTOInnerCard getCard() {
    return card;
  }


  public void setCard(ReturnSearchSaleReturnsResponseSearchResultDTOInnerCard card) {
    
    
    
    this.card = card;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner timeStamp(String timeStamp) {
    
    
    
    
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-11-14T09:26:58.42", value = "")

  public String getTimeStamp() {
    return timeStamp;
  }


  public void setTimeStamp(String timeStamp) {
    
    
    
    this.timeStamp = timeStamp;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner processorStatusCode(String processorStatusCode) {
    
    
    
    
    this.processorStatusCode = processorStatusCode;
    return this;
  }

   /**
   * Get processorStatusCode
   * @return processorStatusCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "A0000", value = "")

  public String getProcessorStatusCode() {
    return processorStatusCode;
  }


  public void setProcessorStatusCode(String processorStatusCode) {
    
    
    
    this.processorStatusCode = processorStatusCode;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner batchStatus(String batchStatus) {
    
    
    
    
    this.batchStatus = batchStatus;
    return this;
  }

   /**
   * Get batchStatus
   * @return batchStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Batch - Closed", value = "")

  public String getBatchStatus() {
    return batchStatus;
  }


  public void setBatchStatus(String batchStatus) {
    
    
    
    this.batchStatus = batchStatus;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner guid(String guid) {
    
    
    
    
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "451dd720-18e6-48b2-a8fa-b9ae4579c3fc", value = "")

  public String getGuid() {
    return guid;
  }


  public void setGuid(String guid) {
    
    
    
    this.guid = guid;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner relatedVoid(Object relatedVoid) {
    
    
    
    
    this.relatedVoid = relatedVoid;
    return this;
  }

   /**
   * Get relatedVoid
   * @return relatedVoid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getRelatedVoid() {
    return relatedVoid;
  }


  public void setRelatedVoid(Object relatedVoid) {
    
    
    
    this.relatedVoid = relatedVoid;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner deviceGuid(String deviceGuid) {
    
    
    
    
    this.deviceGuid = deviceGuid;
    return this;
  }

   /**
   * Get deviceGuid
   * @return deviceGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "8ec1c40b-0c00-4a57-a9c7-7800bd52c308", value = "")

  public String getDeviceGuid() {
    return deviceGuid;
  }


  public void setDeviceGuid(String deviceGuid) {
    
    
    
    this.deviceGuid = deviceGuid;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner type(String type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "CreditReturn", value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    
    
    
    this.type = type;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner cardDataSource(String cardDataSource) {
    
    
    
    
    this.cardDataSource = cardDataSource;
    return this;
  }

   /**
   * Get cardDataSource
   * @return cardDataSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "", value = "")

  public String getCardDataSource() {
    return cardDataSource;
  }


  public void setCardDataSource(String cardDataSource) {
    
    
    
    this.cardDataSource = cardDataSource;
  }


  public ReturnSearchSaleReturnsResponseSearchResultDTOInner allowCardEmv(Boolean allowCardEmv) {
    
    
    
    
    this.allowCardEmv = allowCardEmv;
    return this;
  }

   /**
   * Get allowCardEmv
   * @return allowCardEmv
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getAllowCardEmv() {
    return allowCardEmv;
  }


  public void setAllowCardEmv(Boolean allowCardEmv) {
    
    
    
    this.allowCardEmv = allowCardEmv;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReturnSearchSaleReturnsResponseSearchResultDTOInner instance itself
   */
  public ReturnSearchSaleReturnsResponseSearchResultDTOInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnSearchSaleReturnsResponseSearchResultDTOInner returnSearchSaleReturnsResponseSearchResultDTOInner = (ReturnSearchSaleReturnsResponseSearchResultDTOInner) o;
    return Objects.equals(this.status, returnSearchSaleReturnsResponseSearchResultDTOInner.status) &&
        Objects.equals(this.amount, returnSearchSaleReturnsResponseSearchResultDTOInner.amount) &&
        Objects.equals(this.card, returnSearchSaleReturnsResponseSearchResultDTOInner.card) &&
        Objects.equals(this.timeStamp, returnSearchSaleReturnsResponseSearchResultDTOInner.timeStamp) &&
        Objects.equals(this.processorStatusCode, returnSearchSaleReturnsResponseSearchResultDTOInner.processorStatusCode) &&
        Objects.equals(this.batchStatus, returnSearchSaleReturnsResponseSearchResultDTOInner.batchStatus) &&
        Objects.equals(this.guid, returnSearchSaleReturnsResponseSearchResultDTOInner.guid) &&
        Objects.equals(this.relatedVoid, returnSearchSaleReturnsResponseSearchResultDTOInner.relatedVoid) &&
        Objects.equals(this.deviceGuid, returnSearchSaleReturnsResponseSearchResultDTOInner.deviceGuid) &&
        Objects.equals(this.type, returnSearchSaleReturnsResponseSearchResultDTOInner.type) &&
        Objects.equals(this.cardDataSource, returnSearchSaleReturnsResponseSearchResultDTOInner.cardDataSource) &&
        Objects.equals(this.allowCardEmv, returnSearchSaleReturnsResponseSearchResultDTOInner.allowCardEmv)&&
        Objects.equals(this.additionalProperties, returnSearchSaleReturnsResponseSearchResultDTOInner.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, amount, card, timeStamp, processorStatusCode, batchStatus, guid, relatedVoid, deviceGuid, type, cardDataSource, allowCardEmv, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnSearchSaleReturnsResponseSearchResultDTOInner {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    processorStatusCode: ").append(toIndentedString(processorStatusCode)).append("\n");
    sb.append("    batchStatus: ").append(toIndentedString(batchStatus)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    relatedVoid: ").append(toIndentedString(relatedVoid)).append("\n");
    sb.append("    deviceGuid: ").append(toIndentedString(deviceGuid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    cardDataSource: ").append(toIndentedString(cardDataSource)).append("\n");
    sb.append("    allowCardEmv: ").append(toIndentedString(allowCardEmv)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("amount");
    openapiFields.add("card");
    openapiFields.add("timeStamp");
    openapiFields.add("processorStatusCode");
    openapiFields.add("batchStatus");
    openapiFields.add("guid");
    openapiFields.add("relatedVoid");
    openapiFields.add("deviceGuid");
    openapiFields.add("type");
    openapiFields.add("cardDataSource");
    openapiFields.add("allowCardEmv");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReturnSearchSaleReturnsResponseSearchResultDTOInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReturnSearchSaleReturnsResponseSearchResultDTOInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReturnSearchSaleReturnsResponseSearchResultDTOInner is not found in the empty JSON string", ReturnSearchSaleReturnsResponseSearchResultDTOInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `card`
      if (jsonObj.get("card") != null && !jsonObj.get("card").isJsonNull()) {
        ReturnSearchSaleReturnsResponseSearchResultDTOInnerCard.validateJsonObject(jsonObj.getAsJsonObject("card"));
      }
      if ((jsonObj.get("timeStamp") != null && !jsonObj.get("timeStamp").isJsonNull()) && !jsonObj.get("timeStamp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timeStamp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeStamp").toString()));
      }
      if ((jsonObj.get("processorStatusCode") != null && !jsonObj.get("processorStatusCode").isJsonNull()) && !jsonObj.get("processorStatusCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `processorStatusCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("processorStatusCode").toString()));
      }
      if ((jsonObj.get("batchStatus") != null && !jsonObj.get("batchStatus").isJsonNull()) && !jsonObj.get("batchStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `batchStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("batchStatus").toString()));
      }
      if ((jsonObj.get("guid") != null && !jsonObj.get("guid").isJsonNull()) && !jsonObj.get("guid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `guid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("guid").toString()));
      }
      if ((jsonObj.get("deviceGuid") != null && !jsonObj.get("deviceGuid").isJsonNull()) && !jsonObj.get("deviceGuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deviceGuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deviceGuid").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("cardDataSource") != null && !jsonObj.get("cardDataSource").isJsonNull()) && !jsonObj.get("cardDataSource").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardDataSource` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardDataSource").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReturnSearchSaleReturnsResponseSearchResultDTOInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReturnSearchSaleReturnsResponseSearchResultDTOInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReturnSearchSaleReturnsResponseSearchResultDTOInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReturnSearchSaleReturnsResponseSearchResultDTOInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ReturnSearchSaleReturnsResponseSearchResultDTOInner>() {
           @Override
           public void write(JsonWriter out, ReturnSearchSaleReturnsResponseSearchResultDTOInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReturnSearchSaleReturnsResponseSearchResultDTOInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ReturnSearchSaleReturnsResponseSearchResultDTOInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReturnSearchSaleReturnsResponseSearchResultDTOInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReturnSearchSaleReturnsResponseSearchResultDTOInner
  * @throws IOException if the JSON string is invalid with respect to ReturnSearchSaleReturnsResponseSearchResultDTOInner
  */
  public static ReturnSearchSaleReturnsResponseSearchResultDTOInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReturnSearchSaleReturnsResponseSearchResultDTOInner.class);
  }

 /**
  * Convert an instance of ReturnSearchSaleReturnsResponseSearchResultDTOInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

