/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UpdatePayeeDto
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UpdatePayeeDto {
  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_ADDRESS1 = "address1";
  @SerializedName(SERIALIZED_NAME_ADDRESS1)
  private String address1;

  public static final String SERIALIZED_NAME_ADDRESS2 = "address2";
  @SerializedName(SERIALIZED_NAME_ADDRESS2)
  private String address2;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_ZIP_CODE = "zipCode";
  @SerializedName(SERIALIZED_NAME_ZIP_CODE)
  private String zipCode;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public UpdatePayeeDto() {
  }

  public UpdatePayeeDto firstName(String firstName) {
    
    
    if (firstName != null && firstName.length() < 0) {
      throw new IllegalArgumentException("Invalid value for firstName. Length must be greater than or equal to 0.");
    }
    
    this.firstName = firstName;
    return this;
  }

   /**
   * First name for the Payee to be updated.
   * @return firstName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "First name for the Payee to be updated.")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    
    
    if (firstName != null && firstName.length() < 0) {
      throw new IllegalArgumentException("Invalid value for firstName. Length must be greater than or equal to 0.");
    }
    this.firstName = firstName;
  }


  public UpdatePayeeDto lastName(String lastName) {
    
    
    if (lastName != null && lastName.length() < 0) {
      throw new IllegalArgumentException("Invalid value for lastName. Length must be greater than or equal to 0.");
    }
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Last name for the Payee to be updated.
   * @return lastName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Last name for the Payee to be updated.")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    
    
    if (lastName != null && lastName.length() < 0) {
      throw new IllegalArgumentException("Invalid value for lastName. Length must be greater than or equal to 0.");
    }
    this.lastName = lastName;
  }


  public UpdatePayeeDto email(String email) {
    
    
    
    
    this.email = email;
    return this;
  }

   /**
   * Email address for the Payee to be updated.
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Email address for the Payee to be updated.")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    
    
    
    this.email = email;
  }


  public UpdatePayeeDto address1(String address1) {
    
    
    if (address1 != null && address1.length() < 0) {
      throw new IllegalArgumentException("Invalid value for address1. Length must be greater than or equal to 0.");
    }
    
    this.address1 = address1;
    return this;
  }

   /**
   * Postal address line 1 for the Payee to be updated. Alphanumerics and [,.-&#39;] are allowed.
   * @return address1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Postal address line 1 for the Payee to be updated. Alphanumerics and [,.-'] are allowed.")

  public String getAddress1() {
    return address1;
  }


  public void setAddress1(String address1) {
    
    
    if (address1 != null && address1.length() < 0) {
      throw new IllegalArgumentException("Invalid value for address1. Length must be greater than or equal to 0.");
    }
    this.address1 = address1;
  }


  public UpdatePayeeDto address2(String address2) {
    
    
    if (address2 != null && address2.length() < 0) {
      throw new IllegalArgumentException("Invalid value for address2. Length must be greater than or equal to 0.");
    }
    
    this.address2 = address2;
    return this;
  }

   /**
   * Postal address line 2 for the Payee to be updated. Alphanumerics and [,.-&#39;] are allowed.
   * @return address2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Postal address line 2 for the Payee to be updated. Alphanumerics and [,.-'] are allowed.")

  public String getAddress2() {
    return address2;
  }


  public void setAddress2(String address2) {
    
    
    if (address2 != null && address2.length() < 0) {
      throw new IllegalArgumentException("Invalid value for address2. Length must be greater than or equal to 0.");
    }
    this.address2 = address2;
  }


  public UpdatePayeeDto city(String city) {
    
    
    if (city != null && city.length() < 0) {
      throw new IllegalArgumentException("Invalid value for city. Length must be greater than or equal to 0.");
    }
    
    this.city = city;
    return this;
  }

   /**
   * Postal address city for the Payee to be updated.
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Postal address city for the Payee to be updated.")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    
    
    if (city != null && city.length() < 0) {
      throw new IllegalArgumentException("Invalid value for city. Length must be greater than or equal to 0.");
    }
    this.city = city;
  }


  public UpdatePayeeDto state(String state) {
    
    
    if (state != null && state.length() < 0) {
      throw new IllegalArgumentException("Invalid value for state. Length must be greater than or equal to 0.");
    }
    
    this.state = state;
    return this;
  }

   /**
   * Postal address state for the Payee to be updated.
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Postal address state for the Payee to be updated.")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    
    
    if (state != null && state.length() < 0) {
      throw new IllegalArgumentException("Invalid value for state. Length must be greater than or equal to 0.");
    }
    this.state = state;
  }


  public UpdatePayeeDto zipCode(String zipCode) {
    
    
    if (zipCode != null && zipCode.length() < 0) {
      throw new IllegalArgumentException("Invalid value for zipCode. Length must be greater than or equal to 0.");
    }
    
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Postal code for the Payee to be updated.
   * @return zipCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Postal code for the Payee to be updated.")

  public String getZipCode() {
    return zipCode;
  }


  public void setZipCode(String zipCode) {
    
    
    if (zipCode != null && zipCode.length() < 0) {
      throw new IllegalArgumentException("Invalid value for zipCode. Length must be greater than or equal to 0.");
    }
    this.zipCode = zipCode;
  }


  public UpdatePayeeDto phone(String phone) {
    
    
    
    
    this.phone = phone;
    return this;
  }

   /**
   * Phone number for the Payee to be updated, up to 10-character string.
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Phone number for the Payee to be updated, up to 10-character string.")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    
    
    
    this.phone = phone;
  }


  public UpdatePayeeDto status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Status for the Payee to be updated.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status for the Payee to be updated.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdatePayeeDto instance itself
   */
  public UpdatePayeeDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePayeeDto updatePayeeDto = (UpdatePayeeDto) o;
    return Objects.equals(this.firstName, updatePayeeDto.firstName) &&
        Objects.equals(this.lastName, updatePayeeDto.lastName) &&
        Objects.equals(this.email, updatePayeeDto.email) &&
        Objects.equals(this.address1, updatePayeeDto.address1) &&
        Objects.equals(this.address2, updatePayeeDto.address2) &&
        Objects.equals(this.city, updatePayeeDto.city) &&
        Objects.equals(this.state, updatePayeeDto.state) &&
        Objects.equals(this.zipCode, updatePayeeDto.zipCode) &&
        Objects.equals(this.phone, updatePayeeDto.phone) &&
        Objects.equals(this.status, updatePayeeDto.status)&&
        Objects.equals(this.additionalProperties, updatePayeeDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, email, address1, address2, city, state, zipCode, phone, status, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePayeeDto {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("firstName");
    openapiFields.add("lastName");
    openapiFields.add("email");
    openapiFields.add("address1");
    openapiFields.add("address2");
    openapiFields.add("city");
    openapiFields.add("state");
    openapiFields.add("zipCode");
    openapiFields.add("phone");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UpdatePayeeDto
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UpdatePayeeDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdatePayeeDto is not found in the empty JSON string", UpdatePayeeDto.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("firstName") != null && !jsonObj.get("firstName").isJsonNull()) && !jsonObj.get("firstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstName").toString()));
      }
      if ((jsonObj.get("lastName") != null && !jsonObj.get("lastName").isJsonNull()) && !jsonObj.get("lastName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("address1") != null && !jsonObj.get("address1").isJsonNull()) && !jsonObj.get("address1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address1").toString()));
      }
      if ((jsonObj.get("address2") != null && !jsonObj.get("address2").isJsonNull()) && !jsonObj.get("address2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address2").toString()));
      }
      if ((jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) && !jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if ((jsonObj.get("zipCode") != null && !jsonObj.get("zipCode").isJsonNull()) && !jsonObj.get("zipCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `zipCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zipCode").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdatePayeeDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdatePayeeDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdatePayeeDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdatePayeeDto.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdatePayeeDto>() {
           @Override
           public void write(JsonWriter out, UpdatePayeeDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdatePayeeDto read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UpdatePayeeDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdatePayeeDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdatePayeeDto
  * @throws IOException if the JSON string is invalid with respect to UpdatePayeeDto
  */
  public static UpdatePayeeDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdatePayeeDto.class);
  }

 /**
  * Convert an instance of UpdatePayeeDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

