/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.time.LocalDate;
import com.konfigthis.client.model.ReplayPurchaseEventHistoryResendRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReplayApi
 */
@Disabled
public class ReplayApiTest {

    private static ReplayApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ReplayApi(apiClient);
    }

    /**
     * Purchase Event History (Replay Webhooks)
     *
     * Call this endpoint to receive VCC, Lodged Card, Physical Card or ACH purchase events either by unique Guid or for a specified date range. If you subscribe to webhooks and are concerned you may be missing events, this endpoint can retrieve past events.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void purchaseEventHistoryResendTest() throws ApiException {
        String sourceGuid = null;
        String merchantGuid = null;
        String eventGuid = null;
        LocalDate fromDateTime = null;
        LocalDate toDateTime = null;
        String response = api.purchaseEventHistoryResend()
                .sourceGuid(sourceGuid)
                .merchantGuid(merchantGuid)
                .eventGuid(eventGuid)
                .fromDateTime(fromDateTime)
                .toDateTime(toDateTime)
                .execute();
        // TODO: test validations
    }

}
