/*
 * ConnexPay Reporting API
 * REST API for retrieving reporting data. Currently Daily Accounting data only.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.VerificationCardBankAccountRequest;
import com.konfigthis.client.model.VerificationCardBankAccountRequestBankAccount;
import com.konfigthis.client.model.VerificationCardBankAccountRequestCard;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VerificationApi
 */
@Disabled
public class VerificationApiTest {

    private static VerificationApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new VerificationApi(apiClient);
    }

    /**
     * Verify
     *
     * Call to Verify Card or Bank Account
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cardBankAccountTest() throws ApiException {
        String deviceGuid = null;
        VerificationCardBankAccountRequestCard card = null;
        VerificationCardBankAccountRequestBankAccount bankAccount = null;
        Object response = api.cardBankAccount(deviceGuid)
                .card(card)
                .bankAccount(bankAccount)
                .execute();
        // TODO: test validations
    }

}
